### ISSUE TITLE
Kubernetes: handle sigterm to support graceful shutdown 

### ISSUE THREAD

**Issue by genesis32** [ory/graceful#3]
Hi, this is a minor nit (let me know if you want me to submit a PR to fix it).  Basically when containers are shutting down in Kubernetes they are sent a SIGTERM on PID 1.  The docker images you have for hydra are awesome but hydra only gracefully shuts down on a SIGINT. Supporting both SIGINT and SIGTERM seems sane. I think we can work around this by checking for a file in the container and deleting it on preStop.

https://github.com/ory/graceful/blob/3193de1e065e469711b7a42abd6092b5b92570e2/http_graceful.go#L58

**Comment by aeneasr** [comment]
Yes, feel free to create a PR! :)
